apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: threat-detection-statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
  - name: keyPrefix
    value: name
scopes:
  - threat-detection-camera-stream-capturer
  - threat-detection-weapon-model-invoker
  - threat-detection-fire-model-invoker
  - threat-detection-ccure-alert-notifier
  - threat-detection-snow-alert-notifier
  - threat-detection-pers-alert-notifier
  - threat-detection-slack-alert-notifier
  - threat-detection-dynamodb-media-indexer
  - threat-detection-api
