apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: threat-detection-pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  # Do not include a consumer group so that the DAPR runtime sets it to APPID
  - name: enableTLS
    value: "false"
scopes:
  - threat-detection-camera-stream-capturer
  - threat-detection-weapon-model-invoker
  - threat-detection-fire-model-invoker
  - threat-detection-ccure-alert-notifier
  - threat-detection-snow-alert-notifier
  - threat-detection-pers-alert-notifier
  - threat-detection-slack-alert-notifier
  - threat-detection-dynamodb-media-indexer
  - threat-detection-api
